const DISPLAY_ALERT = "SHOW_ALERT";
const CLEAR_ALERT = "CLEAR_ALERT";

const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

const LOGOUT_USER = "LOGOUT_USER";

const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
const SETUP_USER_ERROR = "SETUP_USER_ERROR";

const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

module.exports = {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  REGISTER_USER_BEGIN,
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  SETUP_USER_BEGIN,
  SETUP_USER_ERROR,
  SETUP_USER_SUCCESS,
  TOGGLE_SIDEBAR,
  LOGOUT_USER,
};
